export const phrases = [
    "Nos teus olhos encontro o brilho que ilumina meu caminho, nos teus braços encontro o conforto que acalma minha alma.",
    "Amor é a poesia dos sentidos. Quando juntos, somos versos que se entrelaçam numa bela melodia.",
    "Te amarei até que as estrelas deixem de brilhar e o sol perca seu calor. Meu amor por ti é eterno como o próprio tempo.",
    "No universo do meu coração, és a estrela mais radiante, a luz que guia os meus passos e ilumina os meus dias.",
    "Te amar é como contemplar a beleza de um jardim em plena primavera, onde cada flor é um pedaço do nosso amor que floresce a cada dia.",
    "O que sinto hoje, veio de você e será eternamente por você!",
    "Eu amo você, menina...\nAmo você...",
    "O verdadeiro amor nunca se desgasta. Quanto mais se dá mais se tem.",
    "Duvida da luz dos astros, De que o sol tenha calor, Duvida até da verdade, Mas confia em meu amor.",
    "O amor é o espaço e o tempo tornados sensíveis ao coração.",
    "A distância faz ao amor aquilo que o vento faz ao fogo: apaga o pequeno, inflama o grande.",
    "A medida do amor é amar sem medida.",
    "Amar não é olhar um para o outro, é olhar juntos na mesma direção.",
    "Amar não é aceitar tudo. Aliás: onde tudo é aceito, desconfio que há falta de amor.",
    "A suprema felicidade da vida é ter a convicção de que somos amados.",
    "Aconteça o que acontecer amanhã, ou para o resto da minha vida, agora estou feliz porque te amo.",
    "O dia dos Namorados para mim é todo dia. Não tenho dias marcados para te amar noite e dia.",
    "O amor que sinto por você é aquele que o vento não leva, a distância não separa e a maldade não destrói.",
    "Palavras são incapazes de expressar todo sentimento que tenho por você. Te amo muito.",
    "Sinto dizer, te amo mesmo… está ruim pra disfarçar.",
    "A maior sorte que eu tive na vida foi te conhecer, e minha maior felicidade é ter você comigo.",
    "O verdadeiro amor é exigente, implacável, e, ao mesmo tempo, infinitamente delicado.",
    "As paixões cegam. Mas o verdadeiro amor nos torna lúcidos.",
    "Só existem duas maneiras de te esquecer: de jeito nenhum e de nenhum jeito.",
    "Se meu coração partisse, eu te dava um pedacinho, mas como ele não parte, te dou ele inteirinho.",
];