export const phrases = [
    "Nos teus olhos encontro o brilho que ilumina meu caminho, nos teus braços encontro o conforto que acalma minha alma.",
    "Amor é a poesia dos sentidos. Quando juntos, somos versos que se entrelaçam numa bela melodia.",
    "Te amarei até que as estrelas deixem de brilhar e o sol perca seu calor. Meu amor por ti é eterno como o próprio tempo.",
    "No universo do meu coração, és a estrela mais radiante, a luz que guia os meus passos e ilumina os meus dias.",
    "Te amar é como contemplar a beleza de um jardim em plena primavera, onde cada flor é um pedaço do nosso amor que floresce a cada dia.",
    "O que sinto hoje, veio de você e será eternamente por você!",
    "Eu amo você, menina...\nAmo você...",
    "O verdadeiro amor nunca se desgasta. Quanto mais se dá mais se tem.",
    "Duvida da luz dos astros, De que o sol tenha calor, Duvida até da verdade, Mas confia em meu amor.",
    "O amor é o espaço e o tempo tornados sensíveis ao coração.",
    "A distância faz ao amor aquilo que o vento faz ao fogo: apaga o pequeno, inflama o grande.",
    "A medida do amor é amar sem medida.",
    "Amar não é olhar um para o outro, é olhar juntos na mesma direção.",
    "Amar não é aceitar tudo. Aliás: onde tudo é aceito, desconfio que há falta de amor.",
    "A suprema felicidade da vida é ter a convicção de que somos amados.",
    "Aconteça o que acontecer amanhã, ou para o resto da minha vida, agora estou feliz porque te amo.",
    "O dia dos Namorados para mim é todo dia. Não tenho dias marcados para te amar noite e dia.",
    "O amor que sinto por você é aquele que o vento não leva, a distância não separa e a maldade não destrói.",
    "Palavras são incapazes de expressar todo sentimento que tenho por você. Te amo muito.",
    "Sinto dizer, te amo mesmo… está ruim pra disfarçar.",
    "A maior sorte que eu tive na vida foi te conhecer, e minha maior felicidade é ter você comigo.",
    "O verdadeiro amor é exigente, implacável, e, ao mesmo tempo, infinitamente delicado.",
    "As paixões cegam. Mas o verdadeiro amor nos torna lúcidos.",
    "Só existem duas maneiras de te esquecer: de jeito nenhum e de nenhum jeito.",
    "Se meu coração partisse, eu te dava um pedacinho, mas como ele não parte, te dou ele inteirinho.",
    "O amor é uma luz que não deixa escurecer a vida: é refletida do astro eterno; irradia-se de Deus.",
    "Amar não é apoderar-se do outro para completar-se, mas dar-se ao outro para completá-lo.",
    "Amar é encontrar na felicidade de outro a sua própria felicidade.",
    "Amor é fogo que arde sem se ver.",
    "O amor é a poesia dos sentidos.",
    "O amor é uma força que nos torna capazes de superar a imensa distância entre a alma e o mundo.",
    "O amor é a asa veloz que Deus deu à alma para que ela voe até o céu.",
    "No teu abraço encontro o refúgio perfeito, onde todas as preocupações se dissipam e só existe espaço para o amor.",
    "Contigo descobri que o amor é mais do que palavras, é uma conexão profunda que ultrapassa qualquer obstáculo.",
    "Cada momento ao teu lado é uma página de um conto de fadas, onde o amor é o protagonista e a felicidade o desfecho inevitável.",
    "O teu sorriso é a minha fonte de felicidade, a luz que ilumina os meus dias mais sombrios.",
    "No teu beijo encontro a magia que transforma simples instantes em eternidade.",
    "Teu toque incendeia minha pele, despertando desejos que só você pode satisfazer.",
    "Cada beijo teu é como uma chama ardente que queima em meu corpo, deixando-me ansioso por mais.",
    "Explorar cada curva do teu corpo é como desvendar um mistério que me instiga e me enlouquece.",
    "Quero te amar de formas que te deixem sem fôlego, te levando a um êxtase que só nós dois conhecemos.",
    "Quando eu passo um dia sem falar com você. Pra mim esse dia não tem como ser bom.",
    "Te amo sem saber como, nem quando, nem onde, te amo diretamente sem problemas nem orgulho: assim te amo porque não sei amar de outra maneira.",
];